### ISSUE TITLE
Error in Logs when starting server

### ISSUE THREAD

**Issue by Rouchesta** [PYRRH4/CustomCommands#1]
Server Spigot 1.13.2

`[18:28:59] [Server thread/ERROR]: Could not load 'plugins/CustomCommands_v3.0.2-BETA.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: PyrCore
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:323) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [spigot-1.13.2.jar:git-Spigot-29ab5e4-2bc7d1d]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`

Thank you.
Gaëtan.

**Comment by PYRRH4** [comment]
You need to download PyrCore in order for this plugin to work ^^
