### ISSUE TITLE
Savelocation & Saveitem doesn't Work

### ISSUE THREAD

**Issue by SchattenritterX** [PYRRH4/CustomCommands#10]
### Issue description
I can't use /customcommands saveitem & savelocation

### Versions

Spigot : 1.12.2

PyrCore :  3.2.7

CustomCommands : 2.3.3

### Log file
**Savelocation**
```
[09:31:55] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'customcommands' in plugin CustomCommands v2.3.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at be.pyrrh4.core.command.CallInfo.getArgAsString(CallInfo.java:57) ~[?:?]
	at be.pyrrh4.customcommands.CommandSaveItem.perform(CommandSaveItem.java:16) ~[?:?]
	at be.pyrrh4.core.command.Arguments.perform(Arguments.java:288) ~[?:?]
	at be.pyrrh4.core.command.Command.onCommand(Command.java:184) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	... 15 more
```

**Savelocation**
```
[09:28:07] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'customcommands' in plugin CustomCommands v2.3.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at be.pyrrh4.core.command.CallInfo.getArgAsString(CallInfo.java:57) ~[?:?]
	at be.pyrrh4.customcommands.CommandSaveLocation.perform(CommandSaveLocation.java:15) ~[?:?]
	at be.pyrrh4.core.command.Arguments.perform(Arguments.java:288) ~[?:?]
	at be.pyrrh4.core.command.Command.onCommand(Command.java:184) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	... 15 more
```

**Comment by PYRRH4** [comment]
Fixed in [CustomCommands v2.3.4](https://www.spigotmc.org/resources/14363/update?update=218280)
